from . import add_button
from . import add_button_in
from . import add_video
from . import add_questions
from . import del_button
from . import del_button_in
from . import del_video
from . import del_questions
from . import admin
from . import page