# Generated by Django 5.0.7 on 2024-07-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionStudent',
            new_name='ApplicantOption',
        ),
        migrations.RenameModel(
            old_name='QuestionApplicant',
            new_name='ApplicantQuestion',
        ),
        migrations.RenameModel(
            old_name='OptionApplicant',
            new_name='StudentOption',
        ),
        migrations.RenameModel(
            old_name='QuestionStudent',
            new_name='StudentQuestion',
        ),
    ]
