# Generated by Django 5.0.7 on 2024-07-31 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_rename_optionstudent_applicantoption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(default=1, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='quiz.applicantoption'),
        ),
        migrations.AlterField(
            model_name='applicantoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.applicantquestion'),
        ),
        migrations.AlterField(
            model_name='student',
            name='selected_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quiz.studentoption'),
        ),
        migrations.AlterField(
            model_name='studentoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.studentquestion'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
